### ISSUE TITLE
Функция, която да изпълни цялата азбука без прекъсване

### ISSUE THREAD

**Issue by mutebg** [dzhavat/bulgarian-alphabet#2]
Започвма работа по тази функционалнот,
ще използвам кода който вече имаме от PR #1

**Comment by dzhavat** [comment]
Супер! Мислех за това и си го представям с 3 бутона (може да стане и с два, но това ще се „оптимизира“ в последствие) - старт, пауза и стоп.  Всеки си изпълнява съответно неговата функция. Това май е най-простото решение, но пък е добра основа за подобрение.

**Comment by mutebg** [comment]
Пробвах няколко варианта да ползвам наличните функции но се оказа по трудно от колкото си мислех и сега заминавам на почивка така че няма да мога да завърша в близките 2 седмици

**Comment by dzhavat** [comment]
Няма проблем. Благодаря за включването като цяло! 

Наистина тази задача излезе костелив орех. Аз също пробвах и изглежда, че имам някакъв напредък. Скоро ще добавя кода. Надявам се да имаш време след ваканцията да го погледнеш. Може би ще ти даде идея за възможен вариант :) 

Приятна почивка!
